export enum LocallyStoredItemsKeys {
    // /* App */
    // JWT = 'app:jwt',
    // AppLanguage = 'app:language',

   /* MasterData */
   getUserInfo = 'masterdata:UserInfo',
   GetUsers = 'masterdata:Users',
   GetAllUserStore = 'masterdata:UserStore',
   GetStoreLSTByBranchID = 'masterdata:StoreLST',
   GetBranchesList = 'masterdata:BranchesList',
   GetBranchLstForReports = 'masterdata:BranchLstForReports',
   GetAllUserBranchLst = 'masterdata:UserBranchLst',
   GetAllStore = 'masterdata:Stores',
   GetAllBranchs = 'masterdata:Branchs',
   getSetting = 'masterdata:Setting',
   GetCompanyInfo = 'masterdata:CompanyInfo',
   GetAllVATType = 'masterdata:VATType',
   GetBarCodeSettings = 'masterdata:BarCodeSettings',
   GetClassDataByBarCode = 'masterdata:DataByBarCode',
   GetClassesList = 'masterdata:ClassesList',
   GetlassesMasterdata = 'masterdata:ClassesMasterdata',
   GetAllCollectedClassesLst = 'masterdata:CollectedClassesLst',
   GetClassCollectedByClassID = 'masterdata:ClassCollectedByClassID',
   GetAllClassificationLst = 'masterdata:GetAllClassificationLst',
   GetlassesByID = 'masterdata:classesByID',
   GetClassBranchPriceByClassUnitID = 'masterdata:ClassBranchPriceByClassUnitID',
   GetClassUnitListByClassID = 'masterdata:ClassUnitListByClassID',
   GetClassQuantitiesByClassID = 'masterdata:ClassQuantitiesByClassID',
   GetAlternativeClassLstByClassID = 'masterdata:AlternativeClassLstByClassID',
   GetAlternativeClassLstByTagsID = 'masterdata:AlternativeClassLstByTagsID',
   GetCentersCost3List = 'masterdata:CentersCost3List',
   GetAllCostCenter = 'masterdata:CostCenter',
   GetAllEmployeeLST = 'masterdata:EmployeeLST',
   GetAllDepartmentlst = 'masterdata:Departmentlst',
   getChartOfAccLevel4ByLevel3Id = 'masterdata:ChartOfAccLevel4ByLevel3Id',
   getChartOfAcc = 'masterdata:ChartOfAcc',
   GetAllLevel4 = 'masterdata:AllLevel4',
   GetAllLevel3 = 'masterdata:AllLevel3',
   GetChartOfAcc4Lst = 'masterdata:hartOfAcc4Lst',
   GetAccBalanceByIDLevel4BranchID = 'masterdata:AccBalanceByIDLevel4BranchID',
   GetAllCommissary = 'masterdata:AllCommissary',
   GetSupplier = 'masterdata:Supplier',
   GetTaxInvoiceTypesList='masterdata:taxInvoiceTypes',
   GetAllPOSClasses='masterdata:AllPOSClasses',
   GetPOSCategoryButtons='masterdata:GetPOSCategoryButtons',
   GetPOSItemButtons='masterdata:GetPOSItemButtons',
   GetPOSClassByBarCode='masterdata:GetPOSClassByBarCode',
   GetPOSClassByClassUnitID='masterdata:GetPOSClassByClassUnitID',
   GetCustomersList='masterdata:customersList',
   GetBranchById='masterdata:BranchById',
   GetAllCentersCost1='masterdata:CentersCost1',
   GetAllCentersCost2='masterdata:CentersCost2',
   GetAllCentersCost3='masterdata:CentersCost3',
   GetCustomerOrSupporterByID='masterdata:GetCustomerOrSupporterByID',
}
